# Generated by Django 6.0.4 on 2026-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.CharField(max_length=10)),
                ('headache', models.CharField(max_length=10)),
                ('nausea', models.CharField(max_length=10)),
                ('vomiting', models.CharField(max_length=10)),
                ('fatigue', models.CharField(max_length=10)),
                ('joint_pain', models.CharField(max_length=10)),
                ('skin_rash', models.CharField(max_length=10)),
                ('cough', models.CharField(max_length=10)),
                ('weight_loss', models.CharField(max_length=10)),
                ('yellow_eyes', models.CharField(max_length=10)),
                ('res', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
