# Generated by Django 6.0.4 on 2026-04-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField()),
                ('fee', models.IntegerField()),
                ('available_today', models.BooleanField(default=True)),
                ('location', models.CharField(default='Kanpur, UP', max_length=200)),
                ('diseases', models.TextField(help_text='Comma-separated disease names this doctor treats')),
                ('avatar_initials', models.CharField(default='DR', max_length=3)),
                ('avatar_color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Patient', max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.doctor')),
            ],
        ),
    ]
